#!/usr/bin/env python3

from __future__ import annotations

import argparse
from dataclasses import dataclass
from pathlib import Path


@dataclass(frozen=True)
class ExampleCase:
    name: str
    from_file: Path
    to_file: Path
    plan_file: Path | None


def anchor_for_case(case_name: str) -> str:
    return case_name.replace("_", "-")


def display_case_name(case_name: str) -> str:
    return case_name.replace("_", " ")


def read_text(path: Path) -> str:
    return path.read_text(encoding="utf-8").rstrip()


def strip_static_import_lines(src: str) -> str:
    lines = src.splitlines()
    filtered = [line for line in lines if not line.startswith("from __static__ import ")]
    while len(filtered) > 0 and filtered[0].strip() == "":
        filtered.pop(0)
    return "\n".join(filtered).rstrip()


def collect_cases(example_dir: Path) -> list[ExampleCase]:
    out: list[ExampleCase] = []
    from_files = sorted(example_dir.glob("*.from.py"))
    assert len(from_files) > 0, f"no .from.py files found in {example_dir}"

    for from_file in from_files:
        case_name = from_file.name[: -len(".from.py")]
        to_file = example_dir / f"{case_name}.to.py"
        assert to_file.exists(), f"missing .to.py pair for {from_file.name}"
        plan_candidate = example_dir / f"{case_name}.plan.txt"
        plan_file = plan_candidate if plan_candidate.exists() else None
        out.append(ExampleCase(case_name, from_file, to_file, plan_file))
    return out


def build_readme(cases: list[ExampleCase], script_rel_path: str) -> str:
    lines: list[str] = []
    lines.append("# Transform Examples")
    lines.append("")
    lines.append(f"Generated by `{script_rel_path}`.")
    lines.append("")
    lines.append("Each transform is shown vertically:")
    lines.append("- input")
    lines.append("- expected output")
    lines.append("- display omits `from __static__ import ...` lines")
    lines.append("")
    lines.append("## Cases")
    lines.append("")
    for case in cases:
        pretty = display_case_name(case.name)
        lines.append(f"- [{pretty}](#{anchor_for_case(case.name)})")
    lines.append("")

    for case in cases:
        pretty = display_case_name(case.name)
        lines.append(f"## {pretty}")
        lines.append("")

        left_src = strip_static_import_lines(read_text(case.from_file))
        right_src = strip_static_import_lines(read_text(case.to_file))
        lines.append("From:")
        lines.append("```python")
        lines.append(left_src)
        lines.append("```")
        lines.append("")
        lines.append("To:")
        lines.append("```python")
        lines.append(right_src)
        lines.append("```")
        lines.append("")

    return "\n".join(lines).rstrip() + "\n"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--examples-dir",
        default="tests/pass_examples",
        help="directory containing *.from.py / *.to.py pairs",
    )
    parser.add_argument(
        "--output",
        default="tests/pass_examples/README.md",
        help="output README path",
    )
    args = parser.parse_args()

    repo_root = Path(__file__).resolve().parents[1]
    examples_dir = (repo_root / args.examples_dir).resolve()
    output_path = (repo_root / args.output).resolve()

    assert examples_dir.exists(), f"examples dir not found: {examples_dir}"
    assert examples_dir.is_dir(), f"examples path must be a directory: {examples_dir}"

    cases = collect_cases(examples_dir)
    script_rel = str(Path(__file__).resolve().relative_to(repo_root))
    readme_text = build_readme(cases, script_rel)
    output_path.write_text(readme_text, encoding="utf-8")
    print(f"wrote {output_path}")
    print(f"cases: {len(cases)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
